<?php

namespace Database\Seeders;

use App\Models\FitnessTestLevel;
use Illuminate\Database\Seeder;

class FitnessTestLevelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $levels = [
            // ================= Default Levels for Test ID 1 ================= //
            [
                'test_id' => 1,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Displays limited agility, with inadequate speed, coordination, and flexibility. Demonstrates poor balance and control, executing movements with difficulty, inconsistency and poor coordination. Fails to demonstrate proficiency in agility exercises.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 1,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates essential agility skills, but with inconsistent speed, coordination, and flexibility. Maintains balance and control in basic maneuvers, but frequently encounters challenges with more advanced maneuvers. Competent in fundamental agility exercises.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 1,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates proficient agility, with good speed, coordination, and flexibility. Maintains good balance and control in most situations, occasionally struggling with more challenging maneuvers. Shows competence in a variety of agility exercises.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 1,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Displays advanced agility skills, with very good speed, coordination, and flexibility. Maintains excellent balance and control, demonstrating proficiency in a wide range of maneuvers. Masters complex agility exercises, performing at a consistently high level.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 1,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Demonstrates exceptional agility, characterised by superior speed, coordination, and flexibility. Displays impeccable balance and control in all situations, even during the most challenging maneuvers. Exhibits mastery of advanced agility techniques.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],


            //================== Default Levels for Test ID 2 ================= //
            [
                'test_id' => 2,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Fails to achieve an adequate reach distance, indicating severe lack of flexibility. Struggles to reach even with maximal effort. Demonstrates poor form during the test, with significant discomfort or strain. Shows extreme stiffness that requires intensive flexibility training.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 2,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Achieves a restricted reach distance, suggesting limited flexibility in the lower back and hamstrings. Maintains basic form during the test, but with noticeable discomfort or strain. Shows limited flexibility that requires considerable flexibility training.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 2,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Achieves a good range of motion and fair reach distance, indicating competent flexibility in the lower back and hamstrings. Maintains decent form during the test, though slight discomfort or strain may be evident. Additional stretching and conditioning are recommended.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 2,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Achieves a great range of motion and a very good reach distance, demonstrating ample flexibility in lower back and hamstring and other targeted muscles. Maintains proper form during the test, with controlled movements and minimal strain.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 2,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Achieves an exceptional range of motion, with an outstanding reach distance. Demonstrates extraordinary flexibility in the lower back, hamstrings, and other targeted muscles. Maintains excellent form throughout, with a smooth and controlled movement.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],


            //================== Default Levels for Test ID 3 ================= //
            [
                'test_id' => 3,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Maintains poor balance, with considerable effort and constant adjustments for stability. Demonstrates poor control and steadiness, with excessive sway or wobbling. Holds the test position for a short time, indicating poor proprioceptive abilities.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 3,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Maintains limited balance, with noticeable effort and frequent adjustments for stability. Shows some control and steadiness, but with noticeable sway or wobbling. Holds the test position for a restricted duration, indicating basic proprioceptive abilities.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 3,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Maintains good balance, with moderate effort and occasional adjustments for stability. Shows adequate control and steadiness, with some minor sway or wobbling. Holds the test position for a respectable duration, reflecting solid proprioceptive abilities.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 3,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Maintains excellent balance with minimal effort, possibly with slight adjustments for stability. Shows very good control and steadiness during the test, with minimal sway or wobbling. Holds the position for a considerable duration, indicating strong proprioceptive abilities.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 3,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Maintains perfect balance effortlessly, exhibiting exceptional stability on the standing leg. Demonstrates excellent control and steadiness throughout the test, and holds the test position for the maximum duration with ease, showing superior proprioception.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],

            //================== Default Levels for Test ID 4 ================= //
            [
                'test_id' => 4,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Exhibits weak hand-eye coordination and motor skills. Executes movements with deficient precision and fluidity, with poor timing, accuracy and speed. Needs constant adjustments, showing poor control and synchronisation between hands. Poor efficiency.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 4,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Exhibits restricted hand-eye coordination and motor skills. Executes movements with varying precision, fluidity, timing, accuracy and speed. Shows moderate control and synchronisation between hands, needing noticeable adjustments. Some efficiency.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 4,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Exhibits competent hand-eye coordination and motor skills. Executes movements with precision, fluidity, proper timing, accuracy and speed. Shows good control and synchronisation between hands but may require some adjustments. Good efficiency.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 4,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Exhibits excellent hand-eye coordination and motor skills. Executes movements with high precision, fluidity and very good timing, accuracy and speed. Shows strong control and synchronisation between hands, achieving very high efficiency.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 4,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Exhibits superior hand-eye coordination and motor skills. Executes precise and fluid movements flawlessly, with perfect timing, accuracy and speed. Shows effortless control and synchronisation between hands, achieving maximum efficiency.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],


            //================== Default Levels for Test ID 5 ================= //
            [
                'test_id' => 5,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates poor reaction time, reacting with slow speed. Requires substantial time to process and react to stimuli, with significant delay to the drop, impacting performance. Exhibits poor reflexes and decision-making abilities, needing significant improvement.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 5,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates limited reaction time, reacting with moderate speed and agility. Reacts reasonably promptly to the drop, with a noticeable delay between release and catch. Exhibits restricted reflexes and decision-making abilities.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 5,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates good reaction time, reacting with reasonable speed and agility to stimuli. Reacts quickly to the drop, with a moderate delay between release and catch. Exhibits good reflexes and reactions, demonstrating effective decision-making abilities.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 5,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates very good reaction time, reacting with rapid speed and agility to stimuli. Reacts promptly to the drop, with a short but noticeable delay between release and catch. Exhibits excellent reflexes and efficient decision-making abilities.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 5,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Reacts instantaneously to stimuli, with minimal delay between release and catch. Shows remarkable quickness and precision when responding, demonstrating superior reflexes and reaction speed. Exhibits outstanding reflexes and quick decision-making abilities.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],

            //================== Default Levels for Test ID 6 ================= //
            [
                'test_id' => 6,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates low power, achieving poor performance in the test. Executes the jump with weak explosive force, showing poor lower body strength and explosive power. Exhibits limited technique and form, hindering jump height and efficiency.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 6,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates limited power, achieving modest performance in the test. Executes the jump with moderate explosive force, showing fundamental lower body strength and explosive power. Exhibits basic technique and form, reaching jump height with evident inefficiency.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 6,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates strong power, achieving a good performance in the test. Executes the jump with good explosive force, showing solid lower body strength and explosive power. Exhibits proper technique and form, maximising jump height with reasonable efficiency.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 6,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates very high power, achieving near-top performance in the test. Executes the jump with strong explosive force, showing excellent lower body strength and explosive power. Exhibits solid technique and form, maximising jump height with high efficiency.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 6,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Demonstrates exceptional power, achieving top-tier performance in the test. Executes the jump with explosive force, showing exceptional lower body strength and explosive power. Superior technique and form, maximising jump height with optimal efficiency.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],

            //================== Default Levels for Test ID 7 ================= //
            [
                'test_id' => 7,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates weak grip strength, achieving poor performance on the test. Grip strength measurement indicates weak muscular strength. Exhibits minimal hand and forearm muscle development, showing limited control and endurance, with noticeable fatigue affecting strength.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 7,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates restricted grip strength, achieving modest performance on the test. Grip strength measurement shows limited muscular strength. Exhibits basic hand and forearm muscle development, maintaining strength with some fatigue.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 7,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates good grip strength, achieving solid performance on the test. Grip strength measurement indicates good muscular strength. Exhibits proficient hand and forearm muscle development, maintaining strength with moderate fatigue.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 7,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates very good grip strength, achieving near-top performance on the test. Grip strength measurement reflects strong muscular strength. Exhibits excellent hand and forearm muscle development, maintaining strength with minimal fatigue.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 7,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Demonstrates exceptional grip strength, achieving top-tier performance on the test. Grip strength measurement indicates superior muscular strength. Exhibits outstanding hand and forearm muscle development, maintaining peak strength consistently.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],

            //================== Default Levels for Test ID 8 ================= //
            [
                'test_id' => 8,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates weak muscular endurance, achieving poor performance. Fatigues quickly and is unable to sustain muscle contractions. Exhibits weak core strength and stability, showing limited mental resilience and struggles to sustain the plank.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 8,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates basic muscular endurance, achieving modest performance. Performs exercise with notable effort. Exhibits limited core strength and stability, demonstrating moderate mental resilience, sustaining the plank with significant effort.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 8,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates good muscular endurance, achieving a solid performance. Performs exercise with relative ease. Exhibits good core strength and stability, demonstrating good mental resilience, sustaining the plank with some effort.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 8,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates great muscular endurance, achieving near-top performance. Performs exercise with minimal effort. Exhibits very good core strength and stability. Demonstrates strong mental focus and determination, maintaining the plank with superior stamina.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 8,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Demonstrates exceptional muscular endurance, achieving top-tier performance. Maintains the plank position for a prolonged period. Exhibits outstanding core strength and stability, displaying exceptional mental toughness and resilience, sustaining the plank effortlessly.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],


            // ================== Default Levels for Test ID 9 ================= //
            [
                'test_id' => 9,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates low speed, achieving poor performance in the 30-meter dash. Covers the distance with slow acceleration and velocity. Shows poor form and technique during the sprint, with noticeable inefficiencies. Exhibits little explosiveness.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 9,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates limited speed, achieving moderate performance in the 30-meter dash. Covers the distance with limited acceleration and velocity. Shows potential in form and technique during the sprint but requires refinement. Exhibits some explosiveness.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 9,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates good speed, achieving a solid performance in the 30-meter dash. Covers the distance with proper acceleration and good velocity. Form and technique performed with competence, with minor inefficiencies. Exhibits reasonable explosiveness.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 9,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates very high speed, achieving near-top performance in the 30-meter dash. Covers the distance with rapid acceleration and high velocity. Maintains very good form and technique during the sprint, maximising speed potential. Strong explosiveness.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 9,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Shows exceptional speed, achieving top-tier performance in the 30-meter dash. Covers the distance with exceptional acceleration and velocity. Maintains excellent form and technique throughout the sprint, optimising speed efficiency. Superior explosiveness.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],

            //================== Default Levels for Test ID 10 ================= //
            [
                'test_id' => 10,
                'level' => 1,
                'level_name' => 'Foundation',
                'min_percentage' => 1,
                'max_percentage' => 20,
                'comment' => 'Demonstrates low endurance, achieving poor performance in the test, unable to sustain pace. Shows poor cardiovascular fitness and stamina, requiring substantial improvement. Exhibits limited mental resilience, struggling to cope with fatigue and discomfort.',
                'star_image' => 'uploads/test/images/default-1.jpg',
            ],
            [
                'test_id' => 10,
                'level' => 2,
                'level_name' => 'Participation',
                'min_percentage' => 21,
                'max_percentage' => 40,
                'comment' => 'Demonstrates limited endurance, achieving moderate performance in the test, struggling to maintain pace. Shows limited cardiovascular fitness and stamina. Training is required. Some mental resilience, but additional mental conditioning is needed to improve endurance.',
                'star_image' => 'uploads/test/images/default-2.jpg',
            ],
            [
                'test_id' => 10,
                'level' => 3,
                'level_name' => 'Progression',
                'min_percentage' => 41,
                'max_percentage' => 60,
                'comment' => 'Demonstrates good endurance, achieving a solid performance in the test, displaying consistency and maintaining a steady pace. Shows good cardiovascular fitness and stamina, exhibiting mental resilience to overcome challenges during test.',
                'star_image' => 'uploads/test/images/default-3.jpg',
            ],
            [
                'test_id' => 10,
                'level' => 4,
                'level_name' => 'Performance',
                'min_percentage' => 61,
                'max_percentage' => 80,
                'comment' => 'Demonstrates very good endurance, achieving near-top performance in the test. Sustains a strong pace throughout, showing very good cardiovascular fitness and stamina. Exhibits strong mental focus and determination, maintaining effort despite fatigue.',
                'star_image' => 'uploads/test/images/default-4.jpg',
            ],
            [
                'test_id' => 10,
                'level' => 5,
                'level_name' => 'Elite',
                'min_percentage' => 81,
                'max_percentage' => 100,
                'comment' => 'Demonstrates exceptional endurance, achieving top-tier performance in the test. Maintains a high level of intensity throughout, showing outstanding cardiovascular fitness and stamina. Exceptional mental toughness and resilience, pushing beyond perceived limits.',
                'star_image' => 'uploads/test/images/default-5.jpg',
            ],
        ];

        foreach ($levels as $level) {
            FitnessTestLevel::create($level);
        }
    }
}
