name: Deploy Admin Backend

on:
  push:
    branches:
      - dev

jobs:
  FTP-Deploy-Admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: FTP Deploy Admin
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.fitnessq.net
          username: 214705_backend
          password: 'F@3csVnNtbNWdtFKYd%U'
